development: &development
  adapter: mysql2
  database: "<%= ENV['DATABASE_NAME'] %>"
  username: "<%= ENV['DATABASE_USERNAME'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  pool:     "<%= ENV['DATABASE_POOL'] %>"
  host:     "<%= ENV['DATABASE_HOST'] || '127.0.0.1' %>"
  port:     "<%= ENV['DATABASE_PORT'] || '3306' %>"

test: &test
  adapter: mysql2
  database: "<%= ENV['DATABASE_TEST_NAME'] %>"<%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= ENV['DATABASE_TEST_USERNAME'] %>
  password: <%= ENV['DATABASE_TEST_PASSWORD']%>
  host:     <%= ENV['DATABASE_TEST_HOST'] || '127.0.0.1' %>
  port:     <%= ENV['DATABASE_TEST_PORT'] || '3306' %>
  reconnect: true
  pool:    50
  timeout: 10000
